services:
  api-tarefada:
    build: ./app
    container_name: api-tarefada
    ports:
      - "3000:3000"
    env_file:
      - ./app/.env.local
    volumes:
      - ./app:/app
    restart: unless-stopped
    depends_on:
      - db-tarefada
    networks:
      - tarefada-networks
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db-tarefada:
    image: postgres:15
    container_name: db-tarefada
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tarefada
    ports:
      - "15432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - tarefada-networks

volumes:
  pgdata:

networks:
  tarefada-networks:
    driver: bridge


