name: Build imagem docker

on:
  pull_request:
    branches:
      - develop
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v6

      - name: Build docker
        run: docker compose build